ShapeNetv2_path = 'datasets/ShapeNetCore.v2'
ShapeNetv2_Scans_path = 'datasets/ShapeNetv2_data/scan'
ShapeNetv2_Watertight_path = 'datasets/ShapeNetv2_data/watertight'
ShapeNetv2_Watertight_Scaled_path = 'datasets/ShapeNetv2_data/watertight_scaled'
ShapeNetv2_Watertight_Scaled_Simplified_path = 'datasets/ShapeNetv2_data/watertight_scaled_simplified'